name: churchapp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  pin_code_fields: ^7.0.0
  get: ^4.1.4
  country_list_pick: ^1.0.1+4
  hidden_drawer_menu: ^2.0.1
  url_launcher: ^6.0.3
  webview_flutter: ^2.0.4
  google_fonts: ^2.0.0
  http: ^0.13.1
  http_parser: ^4.0.0
  shared_preferences: ^2.0.5
  path_provider: ^2.0.1
  flutter_svg: ^0.22.0
  firebase_core: ^1.1.0
  firebase_messaging: ^9.1.3
  flutter_local_notifications: ^5.0.0+3
  #  firebase_core: ^1.0.3
  # firebase_messaging: "^8.0.0-dev.13"
  #  firebase_messaging: ^9.1.1
  #  flutter_local_notifications:
  flutter_native_timezone: ^1.0.10
  carousel_pro: ^1.0.0
  flutter_staggered_animations: ^1.0.0
  # circle_wheel_scroll: ^0.0.1+1
  page_transition: ^1.1.7+6
  cube_transition: ^1.0.2
  file_picker: ^3.0.1
  flutter_stack_card: ^0.2.0+1
  find_dropdown: ^1.0.0
  dio: ^4.0.0
  rounded_loading_button: ^1.0.18
  image_picker: ^0.7.4
  flutter_animated_dialog: ^2.0.0
  fancy_bottom_navigation: ^0.3.3
  intl: ^0.17.0
  date_format: ^2.0.2
  analog_clock: ^0.0.4
  day_picker: ^1.0.1
  day_selector: ^1.0.0
  animated_text_kit: ^4.2.0
  animated_background: ^1.0.5
  google_maps_flutter: ^2.0.3
  fab_circular_menu: ^1.0.2
  badges: ^1.2.0
  rxdart: ^0.25.0
#  flutter_aws:
#    git:
#      url: https://github.com/yongjhih/flutter_aws.git
#  amplify_flutter: ^0.1.2
#  amplify_core: ^0.1.2
#  amplify_auth_cognito: ^0.1.2
#  amplify_analytics_pinpoint: ^0.1.2
  open_file: any
  mime_type: ^1.0.0
  flutter_filereader: ^2.2.0
  flutter_easyloading: ^3.0.0
  loading: ^1.0.2
  flutter_launcher_name: ^0.0.1
  mailto: ^2.0.0
  pinch_zoom: ^0.1.0


flutter_launcher_name:
  name: "ST.BARNABAS"

dev_dependencies:
  change_app_package_name: ^1.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # plugin:
    # androidPackage: io.flutter.plugins.aws
    # pluginClass: FlutterAwsPlugin

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - image/

