name: churchapp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.15+15

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  pin_code_fields: ^7.0.0
  get: ^4.1.4
  country_list_pick: ^1.0.1+4
  url_launcher: ^6.0.3
  webview_flutter: ^3.0.0
  google_fonts: ^2.0.0
  http: ^0.13.1
  http_parser: ^4.0.0
  shared_preferences: ^2.0.5
  path_provider: ^2.0.1
  flutter_svg: ^1.0.3
  firebase_core: ^1.1.0
  firebase_messaging: ^11.2.8
  flutter_local_notifications: ^9.4.0
  flutter_native_timezone: ^2.0.0
  carousel_pro: ^1.0.0
  flutter_staggered_animations: ^1.0.0
  # circle_wheel_scroll: ^0.0.1+1
  file_picker: ^4.5.0
  rounded_loading_button: ^2.0.5
  intl: ^0.17.0
  date_format: ^2.0.2
  syncfusion_flutter_calendar: ^19.1.63
  google_maps_flutter: ^2.0.3
  fab_circular_menu: ^1.0.2
  badges: ^2.0.2
  rxdart: ^0.27.3
  find_dropdown: ^1.0.0
  toggle_switch: ^1.4.0
  dio: ^4.0.0
  image_picker: ^0.8.4+10
  flutter_easyloading: ^3.0.0
  loading: ^1.0.2
  syncfusion_flutter_pdfviewer: ^19.1.66-beta
  flutter_linkify: ^5.0.2
  carousel_slider: ^4.0.0
  firebase_crashlytics: ^2.0.3
  cached_network_image: ^3.2.0
  package_info_plus: ^1.0.6
  pull_to_refresh: ^2.0.0
  path: ^1.8.0
  photo_view: ^0.13.0
  video_player: ^2.2.5

dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  change_app_package_name: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "image/logo_red.jpeg"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # plugin:
    # androidPackage: io.flutter.plugins.aws
    # pluginClass: FlutterAwsPlugin

  # To add assets to your application, add an assets section, like this:
  assets:
    - image/

